export const GENRE_OPTIONS = [
  "Hip-Hop / Rap",
  "R&B / Soul",
  "Pop",
  "Rock",
  "Electronic / EDM",
  "Country",
  "Jazz",
  "Classical",
  "Latin",
  "Afrobeats",
  "Reggae / Dancehall",
  "Folk / Acoustic",
  "Metal",
  "Punk",
  "Blues",
  "Gospel / Christian",
  "Indie",
  "Alternative",
  "World Music",
  "Lo-Fi / Ambient",
  "Other",
] as const;

export const GOAL_OPTIONS = [
  "Release music consistently",
  "Build fanbase",
  "Get press coverage",
  "Book more shows",
  "Monetize catalog",
  "Build team",
  "Establish brand identity",
  "Land sync placements",
  "Grow streaming numbers",
  "Launch merchandise",
  "Secure distribution deal",
  "Build email list",
  "Create content strategy",
  "Network with industry",
] as const;

export const CHALLENGE_OPTIONS = [
  "No budget",
  "No team",
  "Don't know where to start",
  "Inconsistent releases",
  "No press contacts",
  "Weak online presence",
  "No distribution setup",
  "Poor branding",
  "Time management",
  "No live performance experience",
  "Lack of industry knowledge",
  "Difficulty monetizing",
] as const;

export const BRAND_ADJECTIVES = [
  "Bold",
  "Authentic",
  "Mysterious",
  "Playful",
  "Refined",
  "Raw",
  "Innovative",
  "Classic",
  "Rebellious",
  "Warm",
  "Dark",
  "Uplifting",
  "Minimalist",
  "Luxurious",
  "Underground",
  "Futuristic",
] as const;

export const PRIORITY_OPTIONS = [
  "Release next single/EP",
  "Build EPK & press kit",
  "Set up business (LLC, PRO)",
  "Launch social media strategy",
  "Book upcoming shows",
  "Create visual identity",
  "Build a release calendar",
  "Start pitching to playlists",
] as const;
